
version: '3'

services:

  webapp:
    build: .
    volumes:
      - ".:/${PROJECT_DIR}"
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "8000:8000"
    tty: true

