
version: '3'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/init:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always
    stdin_open: true
  
  webapp:
    build: .
    volumes:
      - ".:/${PROJECT_DIR}"
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
